export const jobs = [
  {
    id: "senior-qa-consultant",
    title: "Senior QA Consultant",
    department: "Quality Assurance",
    location: "Remote, Europe",
    mode: "Full-time",
    workingStyle: "Hybrid (2 days in London)",
    posted: "Oct 24, 2023",
    salaryRange: "£75k – £95k per year",
    startDate: "January 2024",
    applicationDeadline: "Dec 15, 2023",
    tags: ["QA", "Remote"],                                                                                                                                                 
    summary:
      "Lead global quality assurance initiatives for pharmaceutical clients and ensure GMP standards.",
    overview:
      "At OMO Consultants, we pride ourselves on driving operational excellence. As a Senior QA Consultant, you will shape the quality landscape for our premier clients. You are a strategic technical advisor who ensures every line of code adds measurable business value while maintaining robust, scalable standards.",
    responsibilities: [
      "Partner with client engineering leads to design and implement automation frameworks using Cypress and Playwright.",
      "Lead shift-left testing strategy; integrate automated quality gates into CI/CD.",
      "Perform deep-dive technical audits of QA processes and provide modernization roadmaps.",
      "Mentor and upskill junior engineers in testing best practices and JS/TS excellence.",
      "Collaborate with Product Owners to bridge requirements and high-level business logic through BDD.",
    ],
    expectations: [
      "5+ years professional software QA; 3+ years focused on test automation architecture.",
      "Expert proficiency in TypeScript/JavaScript and modern web architectures.",
      "Proven experience communicating technical risk to senior stakeholders.",
      "Continuous improvement mindset to optimize reliability and speed of test suites.",
      "Fintech or highly regulated industry experience is a plus.",
    ],
    requirements: [
      "8+ years in GMP quality assurance within pharma/biotech",
      "Hands-on experience with inspections and audit readiness",
      "Strong knowledge of EU and FDA regulations",
      "Excellent stakeholder communication skills",
    ],
    email: "careers@omoconsultants.com",
  },
  {
    id: "regulatory-affairs-specialist",
    title: "Regulatory Affairs Specialist",
    department: "Regulatory",
    location: "London, UK",
    mode: "Hybrid",
    workingStyle: "Hybrid (3 days on-site)",
    posted: "Oct 20, 2023",
    salaryRange: "Competitive",
    startDate: "Q1 2024",
    applicationDeadline: "Dec 10, 2023",
    tags: ["Regulatory", "Hybrid"],
    summary:
      "Manage submissions and ensure compliance with EMA and FDA regulations for medical devices and drugs.",
    overview:
      "Join our regulatory team to manage submissions and ensure compliance across EU and US markets. Experience with medical devices is a plus.",
    responsibilities: [
      "Prepare and maintain regulatory submissions for EU/US.",
      "Liaise with Health Authorities and notified bodies.",
      "Review labeling and promotional materials for compliance.",
      "Support post-market surveillance activities.",
    ],
    expectations: [
      "5+ years in Regulatory Affairs.",
      "Strong EMA submission experience.",
      "Excellent written communication.",
      "Device experience is advantageous.",
    ],
    requirements: [
      "5+ years in Regulatory Affairs",
      "Experience with EMA submissions",
      "Familiarity with medical device dossiers is a plus",
      "Strong writing and review skills",
    ],
    email: "careers@omoconsultants.com",
  },
  {
    id: "qp-expert",
    title: "QP Expert (Qualified Person)",
    department: "QP/RP",
    location: "Berlin, Germany",
    mode: "On-site",
    workingStyle: "On-site (Berlin)",
    posted: "Oct 18, 2023",
    salaryRange: "€90k – €120k per year",
    startDate: "Immediate",
    applicationDeadline: "Dec 05, 2023",
    tags: ["QP", "On-site"],
    summary:
      "Batch release oversight for medicinal products with deep knowledge of EU GMP Annex 16.",
    overview:
      "Act as the primary QP for batch release of medicinal products and ensure Annex 16 compliance.",
    responsibilities: [
      "Batch certification and release per EU GMP Annex 16.",
      "Interface with regulators and inspectors.",
      "Oversee quality systems for manufacturing partners.",
    ],
    expectations: [
      "EU QP qualification.",
      "Strong QA/CMC background.",
      "Ability to work on-site in Berlin.",
    ],
    requirements: [
      "EU QP qualification",
      "Experience with batch certification",
      "Ability to liaise with Health Authorities",
      "German and English proficiency",
    ],
    email: "careers@omoconsultants.com",
  },
  {
    id: "clinical-project-manager",
    title: "Clinical Project Manager",
    department: "Clinical",
    location: "US East Coast (Remote)",
    mode: "Remote",
    workingStyle: "Remote (US East Coast)",
    posted: "Oct 18, 2023",
    salaryRange: "$120k – $140k per year",
    startDate: "Q1 2024",
    applicationDeadline: "Dec 12, 2023",
    tags: ["Clinical", "Remote"],
    summary:
      "Coordinate CROs and sites to ensure patient safety and trial success from start to close-out.",
    overview:
      "Oversee clinical trials from planning to close-out. Coordinate with CROs and sites to ensure patient safety and delivery against timelines and budgets.",
    responsibilities: [
      "Lead study planning, start-up, and close-out activities.",
      "Coordinate CROs and vendors to hit timelines and budgets.",
      "Monitor trial risk and patient safety signals.",
    ],
    expectations: [
      "7+ years clinical project management.",
      "CRO oversight experience.",
      "Risk-based monitoring familiarity.",
      "Strong communication and budget management.",
    ],
    requirements: [
      "7+ years clinical project management",
      "Experience with CRO oversight",
      "Risk-based monitoring familiarity",
      "Ability to manage budgets and timelines",
    ],
    email: "careers@omoconsultants.com",
  },
];
