import { Footer, Navbar } from "@/components/sections";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body className="overflow-x-hidden">
        <Navbar />
        <div className="pt-[68px]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
